apiVersion: apps/v1
kind: Deployment
metadata: 
	name: query-depl
spec:
	replicas: 1
	selectors:
		matchLabels:
			app: query
	template:
		metadata:
			labels:
				app: query
		spec:
			containers:
				- name: query
				image: hb/query:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: query-clusterip-srv
spec:
  selector:
    app: query
  ports:
    -name: query
    protocol: TCP
    port: 4000
    targetPort: 4000